listener {
    timeout = 300
    on-timeout = dms ipc call lock lock
}

listener {
    timeout = 360
    on-timeout = wlopm --off \*
    on-resume = wlopm --on \*
}

listener {
    on-sleep = dms ipc call lock lock
}